In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4])

In [3]:
arr2 = np.array([10,20])

In [4]:
np.convolve(arr1,arr2)

array([ 10,  40,  70, 100,  80])

In [5]:
tab1= np.arange(1,26).reshape(5,5)

In [6]:
tab1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [7]:
fil = np.array([[1,0],[0,1]])

In [8]:
import scipy.signal as scisig

In [9]:
scisig.convolve2d(tab1,fil)

array([[ 1,  2,  3,  4,  5,  0],
       [ 6,  8, 10, 12, 14,  5],
       [11, 18, 20, 22, 24, 10],
       [16, 28, 30, 32, 34, 15],
       [21, 38, 40, 42, 44, 20],
       [ 0, 21, 22, 23, 24, 25]])