In [1]:
import numpy as np

In [58]:
X = np.random.randint(0,2,(7,3))

In [59]:
X[:,-1]=1

In [60]:
X[:5,:]

array([[0, 1, 1],
       [1, 1, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 1]])

In [61]:
from sklearn.neural_network import MLPRegressor

In [62]:
mlp = MLPRegressor(solver='lbfgs',activation='logistic', alpha=1e-3, hidden_layer_sizes=(2,1,2),max_iter=800000)

Train the network (fit)

In [63]:
mlp.fit(X,X)

MLPRegressor(activation='logistic', alpha=0.001, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(2, 1, 2), learning_rate='constant',
       learning_rate_init=0.001, max_iter=800000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='lbfgs', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

Test the model

In [64]:
predictions = mlp.predict(X)

Create classification report and confusion matrix

In [65]:
aa = (predictions > 0.5) ^ (X == 1)

In [66]:
np.count_nonzero(aa)

0

In [67]:
predictions

array([[ 0.00799731,  0.9870216 ,  0.99599061],
       [ 0.99202603,  1.00708899,  1.00215747],
       [-0.00285273,  0.01266828,  1.00346966],
       [-0.00285273,  0.01266828,  1.00346966],
       [ 0.00799731,  0.9870216 ,  0.99599061],
       [ 0.00799731,  0.9870216 ,  0.99599061],
       [ 0.99202603,  1.00708899,  1.00215747]])

In [89]:
for i in mlp.coefs_:
    print (i)
    print("******")

[[-1.59819972 -1.28875353]
 [-2.00676832 -1.55912858]
 [ 0.59254119  0.63624681]]
******
[[3.59320135]
 [2.22577439]]
******
[[ 3.93908226 -4.32708942]]
******
[[ 1.83529806 -3.03657902  0.03531744]
 [ 4.26464676 -1.3084583   0.03753732]]
******


In [90]:
mlp.intercepts_

[array([1.27014325, 0.50959231]),
 array([-2.85390798]),
 array([-3.05740639,  0.51050204]),
 array([-1.25210571,  1.87024973,  0.98105176])]

In [91]:
mlp.predict(np.array([0,1,1]).reshape(1,-1))

array([[0.00799731, 0.9870216 , 0.99599061]])

In [15]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [74]:
X

array([[0, 1, 1],
       [1, 1, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 1],
       [0, 1, 1],
       [1, 1, 1]])

In [81]:
s= X[2]
print(s)

[0 0 1]


In [82]:
l1 = sigmoid(np.dot(s,mlp.coefs_[0])+mlp.intercepts_[0])

In [83]:
l2 = sigmoid(np.dot(l1,mlp.coefs_[1])+mlp.intercepts_[1])

In [84]:
l3 = sigmoid(np.dot(l2,mlp.coefs_[2])+mlp.intercepts_[2])

In [85]:
l4 = np.dot(l3,mlp.coefs_[3])+mlp.intercepts_[3]

In [86]:
l4

array([-0.00285273,  0.01266828,  1.00346966])