In [1]:
import numpy as np

First we define our activation function and its derivative

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [3]:
def sigmoid_der(x):
    return x*(1-x)

The training function

In [28]:
def train_NN(x,y,neurnum):
    weights1 = 2*np.random.random((x.shape[1],neurnum)) - 1
    weights2 = 2*np.random.random((neurnum,1)) - 1

    
    for j in range(600000):
        hidden = sigmoid(np.dot(x,weights1))
        output = sigmoid(np.dot(hidden,weights2))
    
        output_error = y - output
                    
        out_delta = output_error * sigmoid_der(output)
    
        hidden_error = out_delta.dot(weights2.T)
        
        hidden_delta = hidden_error * sigmoid_der(hidden)
    
        weights2 += hidden.T.dot(out_delta)
        weights1 += x.T.dot(hidden_delta)   
        
    return weights1,weights2


And the predict function

In [29]:
def predict(inputvec,weights):
    hidden_val = sigmoid(np.dot(inputvec,weights[0]))
    return sigmoid(np.dot(hidden_val,weights[1]))

Simple test

In [6]:
x = np.array([  [0.2, 0.4, 0.9],
                [0.9, 0.2, 0.6],
                [0.3, 0.8, 0.3],
                [0.4, 0.3, 0.1] ])


y = np.array([[0.2],
              [0.4],
              [0.5],
              [0.5]])

w = train_NN(x,y,3)

In [7]:
w

(array([[ 0.31381893,  1.077293  , -1.06318212],
        [ 0.27865014,  0.35385889, -1.07510879],
        [-0.47836339, -0.77442609,  2.03428427]]), array([[ 0.87987534],
        [ 0.90084907],
        [-2.79841409]]))

Test our weights

In [8]:
for i in range(4):
    print(predict(x[i],w))

[0.2]
[0.4]
[0.5]
[0.5]


In [9]:
predict(np.array([0.5,0.7,0.4]),w)

array([0.4887387])

# XOR 

In [30]:
x2 = np.array([ [0, 0, 1],
                [0, 1, 1],
                [1, 0, 1],
                [1, 1, 1] ])

y2 = np.array([[0],
               [1],
               [1],
               [0]])

w = train_NN(x2,y2,2)

In [31]:
w

(array([[  1.53345826,  12.34733136],
        [ -1.52784847, -11.55714864],
        [ -0.11733957,   5.51721134]]), array([[ 34.5647598 ],
        [-22.20264454]]))

In [32]:
for i in range(4):
    print(predict(x2[i],w))

[0.00288821]
[0.9960828]
[0.99636183]
[0.00288787]
